name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Update to the latest version
      - uses: subosito/flutter-action@v2 # Hypothetical new version
      - uses: bluefireteam/flutter-gh-pages@v8 # Hypothetical new version
        with:
          baseHref: /radwan-shsop/
